const InitialTimesheetData = [
  { name: "John Doe", dateOfJoin: "01-Jan-23", client: "ABC Corp", email: "john.doe@example.com", mobile: "+1 234 567 8901", location: "New York, USA", total: 31, worked: 25, payType: "Hourly", payRate: "$20/hr", paidLeave: 3, unpaidLeave: 3, document: null },
  { name: "Jane Smith", dateOfJoin: "15-Feb-22", client: "XYZ Ltd", email: "jane.smith@example.com", mobile: "+1 345 678 9012", location: "London, UK", total: 30, worked: 28, payType: "Daily", payRate: "$160/day", paidLeave: 2, unpaidLeave: 0, document: null },
  { name: "Alex Brown", dateOfJoin: "10-Mar-21", client: "DEF Inc", email: "alex.brown@example.com", mobile: "+44 987 654 3210", location: "Berlin, Germany", total: 31, worked: 27, payType: "Hourly", payRate: "$18/hr", paidLeave: 2, unpaidLeave: 2, document: null },
  { name: "Emily White", dateOfJoin: "05-Apr-20", client: "GHI Tech", email: "emily.white@example.com", mobile: "+91 87654 32109", location: "Bangalore, India", total: 30, worked: 26, payType: "Daily", payRate: "$150/day", paidLeave: 3, unpaidLeave: 1, document: null },
  { name: "Michael Scott", dateOfJoin: "12-May-19", client: "Dunder Mifflin", email: "michael.scott@dundermifflin.com", mobile: "+1 555 123 4567", location: "Scranton, USA", total: 31, worked: 30, payType: "Hourly", payRate: "$5000/month", paidLeave: 1, unpaidLeave: 0, document: null },
  { name: "Dwight Schrute", dateOfJoin: "03-Jun-18", client: "Dunder Mifflin", email: "dwight.schrute@dundermifflin.com", mobile: "+1 555 987 6543", location: "Scranton, USA", total: 31, worked: 29, payType: "Hourly", payRate: "$25/hr", paidLeave: 1, unpaidLeave: 1, document: null },
  { name: "Pam Beesly", dateOfJoin: "25-Jul-17", client: "Dunder Mifflin", email: "pam.beesly@dundermifflin.com", mobile: "+1 555 567 8901", location: "Scranton, USA", total: 30, worked: 28, payType: "Daily", payRate: "$140/day", paidLeave: 2, unpaidLeave: 0, document: null },
  { name: "Jim Halpert", dateOfJoin: "10-Aug-16", client: "Dunder Mifflin", email: "jim.halpert@dundermifflin.com", mobile: "+1 555 234 5678", location: "Scranton, USA", total: 31, worked: 30, payType: "Hourly", payRate: "$5200/month", paidLeave: 1, unpaidLeave: 0, document: null },
  { name: "Kevin Malone", dateOfJoin: "08-Sep-15", client: "Dunder Mifflin", email: "kevin.malone@dundermifflin.com", mobile: "+1 555 345 6789", location: "Scranton, USA", total: 31, worked: 27, payType: "Hourly", payRate: "$15/hr", paidLeave: 2, unpaidLeave: 2, document: null },
  { name: "Stanley Hudson", dateOfJoin: "22-Oct-14", client: "Dunder Mifflin", email: "stanley.hudson@dundermifflin.com", mobile: "+1 555 456 7890", location: "Scranton, USA", total: 30, worked: 25, payType: "Daily", payRate: "$130/day", paidLeave: 3, unpaidLeave: 2, document: null },
  { name: "Ryan Howard", dateOfJoin: "30-Nov-13", client: "Dunder Mifflin", email: "ryan.howard@dundermifflin.com", mobile: "+1 555 567 8901", location: "Scranton, USA", total: 31, worked: 29, payType: "Hourly", payRate: "$22/hr", paidLeave: 1, unpaidLeave: 1, document: null },
  { name: "Toby Flenderson", dateOfJoin: "15-Dec-12", client: "Dunder Mifflin", email: "toby.flenderson@dundermifflin.com", mobile: "+1 555 678 9012", location: "Scranton, USA", total: 30, worked: 27, payType: "Hourly", payRate: "$4800/month", paidLeave: 2, unpaidLeave: 1, document: null },
  { name: "Oscar Martinez", dateOfJoin: "07-Jan-11", client: "Dunder Mifflin", email: "oscar.martinez@dundermifflin.com", mobile: "+1 555 789 0123", location: "Scranton, USA", total: 31, worked: 30, payType: "Hourly", payRate: "$4900/month", paidLeave: 1, unpaidLeave: 0, document: null },
  { name: "Angela Martin", dateOfJoin: "28-Feb-10", client: "Dunder Mifflin", email: "angela.martin@dundermifflin.com", mobile: "+1 555 890 1234", location: "Scranton, USA", total: 31, worked: 29, payType: "Hourly", payRate: "$21/hr", paidLeave: 1, unpaidLeave: 1, document: null },
  { name: "Meredith Palmer", dateOfJoin: "14-Mar-09", client: "Dunder Mifflin", email: "meredith.palmer@dundermifflin.com", mobile: "+1 555 901 2345", location: "Scranton, USA", total: 30, worked: 26, payType: "Daily", payRate: "$120/day", paidLeave: 2, unpaidLeave: 2, document: null },
  { name: "Creed Bratton", dateOfJoin: "05-Apr-08", client: "Dunder Mifflin", email: "creed.bratton@dundermifflin.com", mobile: "+1 555 012 3456", location: "Scranton, USA", total: 31, worked: 25, payType: "Hourly", payRate: "$19/hr", paidLeave: 3, unpaidLeave: 3, document: null },
  { name: "Kelly Kapoor", dateOfJoin: "22-May-07", client: "Dunder Mifflin", email: "kelly.kapoor@dundermifflin.com", mobile: "+1 555 123 4567", location: "Scranton, USA", total: 30, worked: 29, payType: "Daily", payRate: "$135/day", paidLeave: 1, unpaidLeave: 0, document: null },
  { name: "Andy Bernard", dateOfJoin: "11-Jun-06", client: "Dunder Mifflin", email: "andy.bernard@dundermifflin.com", mobile: "+1 555 234 5678", location: "Scranton, USA", total: 31, worked: 30, payType: "Hourly", payRate: "$5100/month", paidLeave: 1, unpaidLeave: 0, document: null },
  { name: "Phyllis Vance", dateOfJoin: "30-Jul-05", client: "Dunder Mifflin", email: "phyllis.vance@dundermifflin.com", mobile: "+1 555 345 6789", location: "Scranton, USA", total: 31, worked: 28, payType: "Hourly", payRate: "$23/hr", paidLeave: 2, unpaidLeave: 1, document: null }
];

export default InitialTimesheetData;