const InitialTimesheetData = [
  { name: "John Doe", email: "john.doe@example.com", role: "Employee", password: "john123", dateOfJoin: "01-Jan-23", client: "ABC Corp", mobile: "+1 234 567 8901", location: "New York, USA", total: 31, worked: 25, payType: "Hourly", payRate: "$20/hr", paidLeave: 3, unpaidLeave: 3, document: null },
  { name: "Jane Smith", email: "jane.smith@example.com", role: "HR", password: "jane123", dateOfJoin: "15-Feb-22", client: "XYZ Ltd", mobile: "+1 345 678 9012", location: "London, UK", total: 30, worked: 28, payType: "Daily", payRate: "$160/day", paidLeave: 2, unpaidLeave: 0, document: null },
  { name: "Alex Brown", email: "alex.brown@example.com", role: "Employee", password: "alex123", dateOfJoin: "10-Mar-21", client: "DEF Inc", mobile: "+44 987 654 3210", location: "Berlin, Germany", total: 31, worked: 27, payType: "Hourly", payRate: "$18/hr", paidLeave: 2, unpaidLeave: 2, document: null },
  { name: "Emily White", email: "emily.white@example.com", role: "HR", password: "emily123", dateOfJoin: "05-Apr-20", client: "GHI Tech", mobile: "+91 87654 32109", location: "Bangalore, India", total: 30, worked: 26, payType: "Daily", payRate: "$150/day", paidLeave: 3, unpaidLeave: 1, document: null },
  { name: "Michael Scott", email: "michael.scott@dundermifflin.com", role: "HR", password: "michael123", dateOfJoin: "12-May-19", client: "Dunder Mifflin", mobile: "+1 555 123 4567", location: "Scranton, USA", total: 31, worked: 30, payType: "Hourly", payRate: "$5000/month", paidLeave: 1, unpaidLeave: 0, document: null },
  { name: "Dwight Schrute", email: "dwight.schrute@dundermifflin.com", role: "Employee", password: "dwight123", dateOfJoin: "03-Jun-18", client: "Dunder Mifflin", mobile: "+1 555 987 6543", location: "Scranton, USA", total: 31, worked: 29, payType: "Hourly", payRate: "$25/hr", paidLeave: 1, unpaidLeave: 1, document: null },
  { name: "Pam Beesly", email: "pam.beesly@dundermifflin.com", role: "Employee", password: "pam123", dateOfJoin: "25-Jul-17", client: "Dunder Mifflin", mobile: "+1 555 567 8901", location: "Scranton, USA", total: 30, worked: 28, payType: "Daily", payRate: "$140/day", paidLeave: 2, unpaidLeave: 0, document: null },
  { name: "Jim Halpert", email: "jim.halpert@dundermifflin.com", role: "Employee", password: "jim123", dateOfJoin: "10-Aug-16", client: "Dunder Mifflin", mobile: "+1 555 234 5678", location: "Scranton, USA", total: 31, worked: 30, payType: "Hourly", payRate: "$5200/month", paidLeave: 1, unpaidLeave: 0, document: null },
  { name: "Kevin Malone", email: "kevin.malone@dundermifflin.com", role: "Employee", password: "kevin123", dateOfJoin: "08-Sep-15", client: "Dunder Mifflin", mobile: "+1 555 345 6789", location: "Scranton, USA", total: 31, worked: 27, payType: "Hourly", payRate: "$15/hr", paidLeave: 2, unpaidLeave: 2, document: null },
  { name: "Stanley Hudson", email: "stanley.hudson@dundermifflin.com", role: "Employee", password: "stanley123", dateOfJoin: "22-Oct-14", client: "Dunder Mifflin", mobile: "+1 555 456 7890", location: "Scranton, USA", total: 30, worked: 25, payType: "Daily", payRate: "$130/day", paidLeave: 3, unpaidLeave: 2, document: null },
  { name: "Ryan Howard", email: "ryan.howard@dundermifflin.com", role: "HR", password: "ryan123", dateOfJoin: "30-Nov-13", client: "Dunder Mifflin", mobile: "+1 555 567 8901", location: "Scranton, USA", total: 31, worked: 29, payType: "Hourly", payRate: "$22/hr", paidLeave: 1, unpaidLeave: 1, document: null },
  { name: "Toby Flenderson", email: "toby.flenderson@dundermifflin.com", role: "HR", password: "toby123", dateOfJoin: "15-Dec-12", client: "Dunder Mifflin", mobile: "+1 555 678 9012", location: "Scranton, USA", total: 30, worked: 27, payType: "Hourly", payRate: "$4800/month", paidLeave: 2, unpaidLeave: 1, document: null },
  { name: "Oscar Martinez", email: "oscar.martinez@dundermifflin.com", role: "HR", password: "oscar123", dateOfJoin: "07-Jan-11", client: "Dunder Mifflin", mobile: "+1 555 789 0123", location: "Scranton, USA", total: 31, worked: 30, payType: "Hourly", payRate: "$4900/month", paidLeave: 1, unpaidLeave: 0, document: null },
  { name: "Angela Martin", email: "angela.martin@dundermifflin.com", role: "Employee", password: "angela123", dateOfJoin: "28-Feb-10", client: "Dunder Mifflin", mobile: "+1 555 890 1234", location: "Scranton, USA", total: 31, worked: 29, payType: "Hourly", payRate: "$21/hr", paidLeave: 1, unpaidLeave: 1, document: null }
];

export default InitialTimesheetData;
